### ISSUE TITLE
build failed on ubuntu 18.04LTS

### ISSUE THREAD

**Issue by johnlofty** [art567/mt7601usta#3]
build failed.

``make -C tools
make[1]: Entering directory '/home/johnlofty/work/drivers/mt7601usta/src/tools'
gcc -g bin2h.c -o bin2h
make[1]: Leaving directory '/home/johnlofty/work/drivers/mt7601usta/src/tools'
/home/johnlofty/work/drivers/mt7601usta/src/tools/bin2h
cp -f os/linux/Makefile.6 /home/johnlofty/work/drivers/mt7601usta/src/os/linux/Makefile
make -C /lib/modules/4.15.0-20-generic/build SUBDIRS=/home/johnlofty/work/drivers/mt7601usta/src/os/linux modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-20-generic'
Makefile:976: "Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel"
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../os/linux/rt_profile.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/assoc.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/auth.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/auth_rsp.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/sync.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/sanity.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/rtmp_data.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/connect.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/wpa.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/sta_cfg.o
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/sta_cfg.c: In function ‘Set_EncrypType_Proc’:
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/sta_cfg.c:1104:5: warning: this ‘else’ clause does not guard... [-Wmisleading-indentation]
     else
     ^~~~
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/sta_cfg.c:1107:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘else’
  if (pAd->StaCfg.BssType == BSS_ADHOC)
  ^~
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/sta_cfg.c: In function ‘RtmpIoctl_rt_ioctl_siwfreq’:
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/sta_cfg.c:6018:5: warning: this ‘else’ clause does not guard... [-Wmisleading-indentation]
     else
     ^~~~
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/sta_cfg.c:6021:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘else’
  return NDIS_STATUS_SUCCESS;
  ^~~~~~
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/sta_cfg.c: In function ‘RtmpIoctl_rt_ioctl_giwrate’:
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/sta_cfg.c:7928:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if (rate_index >= rate_count)
     ^~
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../sta/sta_cfg.c:7931:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  *(ULONG *)pData = ralinkrate[rate_index] * 500000;
  ^
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/crypt_md5.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/crypt_sha2.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/crypt_hmac.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/crypt_aes.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/crypt_arc4.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/mlme.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_wep.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/action.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_data.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/rtmp_init.o
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/rtmp_init.c: In function ‘NICInitializeAsic’:
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/rtmp_init.c:1656:1: warning: the frame size of 1048 bytes is larger than 1024 bytes [-Wframe-larger-than=]
 }
 ^
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/rtmp_init_inf.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_tkip.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_aes.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_sync.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/eeprom.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_sanity.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_info.o
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_info.c: In function ‘GetEncryptType’:
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_info.c:1752:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if(enc == Ndis802_11Encryption3Enabled)
     ^~
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_info.c:1754:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  if(enc == Ndis802_11Encryption4Enabled)
  ^~
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_info.c: In function ‘GetAuthMode’:
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_info.c:1764:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if(auth == Ndis802_11AuthModeShared)
     ^~
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_info.c:1766:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  if(auth == Ndis802_11AuthModeAutoSwitch)
  ^~
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_info.c:1776:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if(auth == Ndis802_11AuthModeWPA2PSK)
     ^~
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_info.c:1778:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  if(auth == Ndis802_11AuthModeWPA1WPA2)
  ^~
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_info.c: In function ‘Show_PMK_Proc’:
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_info.c:4198:5: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
     for (idx = 0; idx < 32; idx++)
     ^~~
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_info.c:4201:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
  return 0;
  ^~~~~~
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_cfg.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_wpa.o
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_wpa.c: In function ‘WPAStart2WayGroupHS’:
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_wpa.c:1257:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if ((!pEntry) || !IS_ENTRY_CLIENT(pEntry))
     ^~
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_wpa.c:1262:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  os_alloc_mem(NULL, (PUCHAR *)&mpool, TX_EAPOL_BUFFER);
  ^~~~~~~~~~~~
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_radar.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/spectrum.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/rtmp_timer.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/rt_channel.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_profile.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_asic.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/scan.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/cmm_cmd.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/uapsd.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/ps.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../rate_ctrl/ra_ctrl.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../rate_ctrl/alg_legacy.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../rate_ctrl/alg_ags.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../chips/rtmp_chip.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/txpower.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../mac/rtmp_mac.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../mgmt/mgmt_hw.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../mgmt/mgmt_entrytb.o
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../mgmt/mgmt_entrytb.c: In function ‘MacTableInsertEntry’:
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../mgmt/mgmt_entrytb.c:103:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  if (pAd->MacTab.Size >= MAX_LEN_OF_MAC_TABLE)
  ^~
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../mgmt/mgmt_entrytb.c:106:3: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
   FirstWcid = 1;
   ^~~~~~~~~
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../phy/rtmp_phy.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../phy/rlt_phy.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../phy/rlt_rf.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/ba_action.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../mgmt/mgmt_ht.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../common/rt_os_util.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../os/linux/sta_ioctl.o
  CC [M]  /home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../os/linux/rt_linux.o
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../os/linux/rt_linux.c: In function ‘__RTMP_OS_Init_Timer’:
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../os/linux/rt_linux.c:120:3: error: implicit declaration of function ‘init_timer’; did you mean ‘init_timers’? [-Werror=implicit-function-declaration]
   init_timer(pTimer);
   ^~~~~~~~~~
   init_timers
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../os/linux/rt_linux.c:121:9: error: ‘OS_NDIS_MINIPORT_TIMER {aka struct timer_list}’ has no member named ‘data’
   pTimer->data = (unsigned long)data;
         ^~
/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../os/linux/rt_linux.c:122:20: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
   pTimer->function = function;
                    ^
cc1: some warnings being treated as errors
scripts/Makefile.build:332: recipe for target '/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../os/linux/rt_linux.o' failed
make[2]: *** [/home/johnlofty/work/drivers/mt7601usta/src/os/linux/../../os/linux/rt_linux.o] Error 1
Makefile:1552: recipe for target '_module_/home/johnlofty/work/drivers/mt7601usta/src/os/linux' failed
make[1]: *** [_module_/home/johnlofty/work/drivers/mt7601usta/src/os/linux] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-20-generic'
Makefile:418: recipe for target 'LINUX' failed
make: *** [LINUX] Error 2

**Comment by ronnin** [comment]
same to me. please fix the bug, thanks in advance.

**Comment by ronnin** [comment]
said "Now that Kernel 4.2 has been released which contains a driver for mt7601u, this repository is now deprecated." 
that is, we don't need to install this driver program on ubuntu 18.04LTS.

but another problem occurs to me: " device descriptor read/64, error -110".

**Comment by art567** [comment]
@johnlofty Exactly. This repo is deprecated and probably incompatible with 4.2+ kernel.
It meant only to be used with older kernel version as described in [README.md](/art567/mt7601usta/blob/master/README.md)
